name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt
      - name: Install dev deps
        run: pip install -r requirements-dev.txt
      - name: Ruff format check
        run: ruff format --check . || true
      - name: Ruff lint
        run: ruff . || true

  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
      - name: Install runtime deps (no heavy TTS model)
        run: pip install -r requirements.txt
      - name: Dry run parser & stitch (non-interactive)
        env:
          DRY_RUN: "1"
          MODE: "2"
        run: python tts_script.py
